# Windows: clang-cl + MSVC ABI + Ninja
# 通过环境变量 ASAPP_DEP_CLANG_TARGET / ASAPP_DEP_ARCH 选择 32/64 位。
# 推荐由 scripts/build.ps1 在 VsDevCmd -arch=x86|amd64 环境中调用。

set(CMAKE_SYSTEM_NAME Windows)

find_program(CMAKE_C_COMPILER NAMES clang-cl clang-cl.exe REQUIRED)
find_program(CMAKE_CXX_COMPILER NAMES clang-cl clang-cl.exe REQUIRED)

set(CMAKE_C_COMPILER "${CMAKE_C_COMPILER}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${CMAKE_CXX_COMPILER}" CACHE FILEPATH "" FORCE)

# 目标 triple：i686-pc-windows-msvc | x86_64-pc-windows-msvc
if(DEFINED ENV{ASAPP_DEP_CLANG_TARGET} AND NOT "$ENV{ASAPP_DEP_CLANG_TARGET}" STREQUAL "")
    set(_ASAPP_CLANG_TARGET "$ENV{ASAPP_DEP_CLANG_TARGET}")
elseif(DEFINED ENV{ASAPP_DEP_ARCH} AND "$ENV{ASAPP_DEP_ARCH}" STREQUAL "x86")
    set(_ASAPP_CLANG_TARGET "i686-pc-windows-msvc")
else()
    set(_ASAPP_CLANG_TARGET "x86_64-pc-windows-msvc")
endif()

set(CMAKE_C_COMPILER_TARGET "${_ASAPP_CLANG_TARGET}" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER_TARGET "${_ASAPP_CLANG_TARGET}" CACHE STRING "" FORCE)

# OpenCV 等依赖 CMAKE_SYSTEM_PROCESSOR 做 CPU baseline；仅设 triple 时该项常为空
if(_ASAPP_CLANG_TARGET MATCHES "^i686")
    set(CMAKE_SYSTEM_PROCESSOR "x86" CACHE STRING "" FORCE)
elseif(_ASAPP_CLANG_TARGET MATCHES "^aarch64|arm64")
    set(CMAKE_SYSTEM_PROCESSOR "ARM64" CACHE STRING "" FORCE)
else()
    set(CMAKE_SYSTEM_PROCESSOR "AMD64" CACHE STRING "" FORCE)
endif()

# MSVC 兼容前端
set(CMAKE_CXX_FLAGS_INIT "/EHsc")
set(CMAKE_C_FLAGS_INIT "")

# Win7 API 面；NOMINMAX 避免 windows.h 的 min/max 宏污染
add_compile_definitions(_WIN32_WINNT=0x0601 WINVER=0x0601 NOMINMAX)

message(STATUS "windows-clang-cl toolchain: target=${_ASAPP_CLANG_TARGET} processor=${CMAKE_SYSTEM_PROCESSOR}")
